### ISSUE TITLE
COMP0039 商法（保险、票据、证券）

### ISSUE THREAD

**Issue by Emanual20** [Emanual20/Emanual20.github.io#105]
https://nkucs.icu/#/courses/grade-3/COMP0039 

 NKUCS，一个充满了「神仙」和「神仙」课程的专业，本网站旨在记录 NKUCS 的信息以及历届学生的评价

**Comment by Limerencece** [comment]
授课时间：2025fall
授课老师：张志坡老师
开卷
题型：3×法条分析 3×制度比较（商法内部or民商法） 4×证券应用题 每道题10分
1.法条分析
证券法第三条三公原则
《首次公开发行股票并上市管理办法》第九条和第十二条立法目的
票据法第十一条但书
2.制度比较
股份和债券（不是股票和债券）
票据法与民法的保证原则
保险法与民法的诚信原则
3.证券应用
鸡蛋篮子两个谚语如何理解（分散/集中投资）
一个有限责任公司向用户出售电话卡，卡内1000元，900卖给用户，一年后退还卡内余额，问是什么类型证券（是债券）
大致情境是甲公司没多少钱，但想融资；投资者想获得高于市场利率的、稳定的回报，让你为甲公司设计发行一种证券
结合具体对象，论述如何成功投资

**Comment by Limerencece** [comment]
> 下面是先前学长/学姐的评论，由于先前发布的法学课程评论都无法正常展示，我帮学长/学姐再发一次

授课时间：2023fall
授课老师：张志坡老师
记忆中的考题：
1.名词解释（6个，4分一个）
（1）期权
（2）一致行动
（3）包销
（4）汇票
（5）人寿保险
2.简答（7个，6分一个）
（1）短线交易规定
（2）收购人义务
（3）市场欺诈理论
3.论述（2个，9分一个）
（1）论述两个谚语（鸡蛋放两篮子)
（2）论述操纵市场及其表现
4.案例（2个，8分一个）
（1）强东和奶茶妹妹（期权，上课讲的例子）
（2）票据追索权（上课也讲过，ppt上也有）
