### ISSUE TITLE
COMP0113 国际法

### ISSUE THREAD

**Issue by Emanual20** [Emanual20/Emanual20.github.io#110]
https://nkucs.icu/#/courses/grade-3/COMP0113 

 NKUCS，一个充满了「神仙」和「神仙」课程的专业，本网站旨在记录 NKUCS 的信息以及历届学生的评价

**Comment by Limerencece** [comment]
2026Spring
白佳玉老师
平时事情较多，我们这届有3次课堂测试，每次10道题左右，时间较紧，需要速速写；除此之外还有一次课堂展示。
好处是期末比较友好，题目都是从平时的课堂测试选出来的，大家能明确知道期末考哪些题；给分应该也还不错（老师说基本都85以上）。

**Comment by Limerencece** [comment]
补充一下，期末考试前老师说考的就是从平时的课堂测试选出来的题，只有简答和论述两个题型，但是实际考试中出现了名词解释，只能硬着头皮编
