### ISSUE TITLE
COMP0114 知识产权法

### ISSUE THREAD

**Issue by Emanual20** [Emanual20/Emanual20.github.io#111]
https://nkucs.icu/#/courses/grade-3/COMP0114 

 NKUCS，一个充满了「神仙」和「神仙」课程的专业，本网站旨在记录 NKUCS 的信息以及历届学生的评价

**Comment by Limerencece** [comment]
授课时间：2025fall
授课老师：向波老师
题型：单选 10×2=20 名词解释 5×4=20 简答 5×6=30 案例分析 2×15=30
1.单选 涉及著作权保护对象、属于著作权合理使用的情形、商标权续展等，比较基础，没有法考那种案例题
2.名词解释
视听作品
广播权
创造性
独占实施许可
商标的使用
3.简答
视听作品著作权归属
著作权法定许可
实用新型审查程序
专利权转让
未注册商标的保护
4.案例
一个著作权侵权案例（第一问判断涉案图片是不是作品，第二问判断侵权，接触+实质性相似）
一个商标侵犯姓名权案例（Jordan和乔丹，印象里上课讲过）
考前老师明确说了案例是一个著作权一个商标权
