### ISSUE TITLE
COMP0121 经济法

### ISSUE THREAD

**Issue by Emanual20** [Emanual20/Emanual20.github.io#113]
https://nkucs.icu/#/courses/grade-3/COMP0121 

 NKUCS，一个充满了「神仙」和「神仙」课程的专业，本网站旨在记录 NKUCS 的信息以及历届学生的评价

**Comment by Limerencece** [comment]
一、期末考试
<题型><数量×每题分值>
1.名词解释4×5
市场支配地位
明码标价
商业贿赂
市场调节价
2.简答2×15
滥用市场支配地位的表现形式
简述消费者权利
3.案例1×20
知情权、欺诈行为
4.论述1×30
以公平和平等为出发点，阐述经济法本质、作用和立法目的

二、授课教师
杨gp老师
最后一节课不会统一划重点，但是杨老师在学期初的时候就明确告诉大家，期末可能考到的内容他会在平时提醒大家，讲的时候会说“记一下”或者“注意一下”，有心的同学请留意~
附本人整个学期记录下来的老师提醒大家可能考到的内容，基本覆盖考题：
经济法本质
为什么要把消费者纳入社会经济法的保护？（私法和经济法之辨析）
消费者四个属性
什么是平等？什么是公平？
知情权？欺诈行为？
个人信息的概念
垄断协议的类型
对竞争关系的解释
横向垄断协议用什么原则？本身违法原则
如何认定具有市场支配地位
什么是市场支配地位？滥用的表现形式？
滥用行政职权的行为类型（行政垄断行为的表现形式）
标识混淆行为的概念、法律构成要件？
什么是商业秘密
商业贿赂
商业贿赂中的回扣
价格形成机制
明码标价
