### ISSUE TITLE
COMP0124 行政法与行政诉讼法

### ISSUE THREAD

**Issue by Emanual20** [Emanual20/Emanual20.github.io#114]
https://nkucs.icu/#/courses/grade-3/COMP0124 

 NKUCS，一个充满了「神仙」和「神仙」课程的专业，本网站旨在记录 NKUCS 的信息以及历届学生的评价

**Comment by Limerencece** [comment]
25Fall
王瑞雪老师
选择 2分8道 名词解释4分6道 简答5分6道 论述15分2道
1.选择
是不定项选择，难度偏大
2.名词解释（忘了一个
不成文法源
行政协议
行政裁决
行政诉讼调解（注意不是行政调解）
行政诉讼撤诉
3.简答
行政处罚的类型
比例原则核心思想
诉讼时效
行政复议和行政诉讼的衔接
举证责任
行政诉讼一审简易程序
4.论述
判决的类型
结合案例/立法例，论述信赖保护原则

**Comment by Limerencece** [comment]
> 下面是先前学长/学姐的评论，由于先前发布的法学课程评论都无法正常展示，我帮学长/学姐再发一次

## 24fall

### 选择题（10分，2分一个）

### 名词解释(30分，5分一个)

行政主体:
行政许可:
行政给付:
行政协议:
行政裁决:
行政赔偿:

### 简答题(40分，8分一个)

比例原则之核心思想：
行政处罚概念和种类：
行政强制措施和行政强制执行之辨析：
举证责任之归属：
行政相对人请求司法救济之期限：

### 论述题(20分，10分一个)

行政程序核心思想：
行政诉讼初审裁决撤销之适用：

**Comment by Limerencece** [comment]
> 下面是先前学长/学姐的评论，由于先前发布的法学课程评论都无法正常展示，我帮学长/学姐再发一次

授课时间：2023fall
授课老师：王瑞雪老师
最后一节课的重点很准，不要在重点中画重点，多注重重点的细节
