### ISSUE TITLE
ECON0211 财税法

### ISSUE THREAD

**Issue by Emanual20** [Emanual20/Emanual20.github.io#124]
https://nkucs.icu/#/courses/grade-3/ECON0211 

 NKUCS，一个充满了「神仙」和「神仙」课程的专业，本网站旨在记录 NKUCS 的信息以及历届学生的评价

**Comment by Limerencece** [comment]
2026Spring
李建人老师
一共就两名同学选课，最后都给了3.7，极其在意绩点的同学慎选
