### ISSUE TITLE
Better Sidebar Maintainance

### ISSUE THREAD

**Issue by Tr0py** [Emanual20/Emanual20.github.io#214]
问题：我想贡献一个新的page，但发现增加page需要手动维护sidebar，有些麻烦。我看到每级目录下的`_sidebar.md`都不一样，就猜想是需要手动维护的。然而这个差事想一想就相当麻烦，因为每次增删改page都需要update好多 sidebar。

提议：`_sidebar.md` 的内容是高度冗余的，且有规律可循。所以我们可以使用一个文件，用脚本recursively地生成各个目录下的`_sidebar.md`. 这样以后的maintainer就可以方便地update sidebar了，且更不容易出错。

具体来说，可以用一个脚本提取各层目录下的`*.md`文件的相对路径`path`, 及其大标题`title`, 并以此构建 `[title](path)`。对于每级目录生成对应parents的link，sibling的link以及children的link，其他的sibling的children的link不生成，就符合当前模式了。

**Comment by Tr0py** [comment]
我找到了更好的解决方法，即使用插件管理sidebar，实现只需要维护单一的`_sidebar.md`就可以生成动态可以展开/折叠的侧面导航栏。在这里：Pull Request https://github.com/Emanual20/Emanual20.github.io/pull/215

**Comment by Emanual20** [comment]
> 问题：我想贡献一个新的page，但发现增加page需要手动维护sidebar，有些麻烦。我看到每级目录下的`_sidebar.md`都不一样，就猜想是需要手动维护的。然而这个差事想一想就相当麻烦，因为每次增删改page都需要update好多 sidebar。
> 
> 提议：`_sidebar.md` 的内容是高度冗余的，且有规律可循。所以我们可以使用一个文件，用脚本recursively地生成各个目录下的`_sidebar.md`. 这样以后的maintainer就可以方便地update sidebar了，且更不容易出错。
> 
> 具体来说，可以用一个脚本提取各层目录下的`*.md`文件的相对路径`path`, 及其大标题`title`, 并以此构建 `[title](path)`。对于每级目录生成对应parents的link，sibling的link以及children的link，其他的sibling的children的link不生成，就符合当前模式了。

抱歉今天一直在外面，晚上回来才有时间回复issue。

首先感谢学长关注，之前在init_courses.py里有生成所有课程页面sidebar的代码，但是这个是参考之前框架改的，泛化性很差很差，一直图省事就手动改了。code review过，已经merge了pr的请求了。再次感谢学长贡献和提出的建议！

**Comment by Tr0py** [comment]
Nice!  问题解决，关闭issue了 :)
这个issue和pr的处理速度其实非常快hh
觉得这是个很有意义的project   
great job :P
